name: Terraform Workflow

on:
  push:
    branches:
      - s3-site
      - s3-site-using-module

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  s3-site-branch-job:
    name: Terraform deploy from ${{ github.ref }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/s3-site'

    defaults:
      run:
        working-directory: terraform/s3-site

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Terraform Initialization
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

  s3-site-using-module-branch-job:
    name: Terraform deploy from ${{ github.ref }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/s3-site-using-module'

    defaults:
      run:
        working-directory: terraform/s3-site-using-module

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Terraform Initialization
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve